"""v1

Revision ID: 0148313a6c1f
Revises: cd3ae220af43
Create Date: 2025-11-12 13:49:20.887525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0148313a6c1f'
down_revision: Union[str, Sequence[str], None] = 'cd3ae220af43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('session', 'access_token')
    op.drop_column('session', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('session', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('session', 'data')
    # ### end Alembic commands ###
